version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog
    ports:
      - "3306:3306"
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
